ASSET_LIST = ['BTCUSDT', 'ETHUSDT', 'ADAUSDT', 'SOLUSDT', 'XRPUSDT','DOGEUSDT',
          'SHIBUSDT','AVAXUSDT','DOTUSDT','LINKUSDT','LTCUSDT','MATICUSDT',
          'FARMUSDT','TNSRUSDT','LEVERUSDT','MEMEUSDT','PEPEUSDT','DODOUSDT',
          'SAGAUSDT','THETAUSDT','FTMUSDT','ALGOUSDT','AAVEUSDT','CHZUSDT',
          'MANAUSDT','IOTAUSDT','WLDUSDT','ONGUSDT']
INTERVALS = '15m'